### ISSUE TITLE
npm package is broken

### ISSUE THREAD

**Issue by lhorie** [isiahmeadows/techtonic#3]
Steps to reproduce:

1 - install as per README: `npm install --save-dev techtonic`
2 - try to require it from a file called `hello.js`: `require("techtonic")`
3 - run `node hello.js`

Expected: noop
Actual: `Error: Cannot find module './lib/techtonic.js'`

Additional info: `node_modules/techtonic` folder contains only `index.js`, `package.json` and `README.md`

**Comment by isiahmeadows** [comment]
Welp...Good catch.

**Comment by isiahmeadows** [comment]
Fixed and published.

**Comment by lhorie** [comment]
Getting the error `Cannot find module './lib/index.js' now`

**Comment by isiahmeadows** [comment]
@lhorie Should be fixed now (and the fix is live).
